services:
  calibre-web-automated-book-downloader-dev:
    extends:
      file: ./docker-compose.yml
      service: calibre-web-automated-book-downloader
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd
    environment:
      DEBUG: true
      APP_ENV: dev
      TZ: Europe/Rome
      USE_DOH: true
      CUSTOM_DNS: cloudflare
      # FlareSolverr environment variables
      USE_CF_BYPASS: true  # Enable Cloudflare bypass, requires FlareSolverr (default: true)
      FLARESOLVERR_URL: "http://flaresolverr:8191"  # URL of the FlareSolverr service
      FLARESOLVERR_PATH: "/v1"  # Path for FlareSolverr API (default: /v1)
      FLARESOLVERR_TIMEOUT: 60000  # Timeout for FlareSolverr requests (default: 60000)
    volumes:
      - /tmp/cwa-book-downloader:/tmp/cwa-book-downloader
      - /tmp/cwa-book-downloader-log:/var/log/cwa-book-downloader
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.22
    container_name: flaresolverr
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: Europe/Rome
    ports:
      - 8191:8191
