services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      TZ: America/New_York
      APP_ENV: prod
      UID: 1000
      GID: 100
      CWA_DB_PATH: /auth/app.db
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      # This is where the books will be downloaded to, usually it would be
      # the same as whatever you gave in "calibre-web-automated"
      - /tmp/data/calibre-web/ingest:/cwa-book-ingest
      # This is the location of CWA's app.db, which contains authentication
      # details
      - /cwa/config/path/app.db:/auth/app.db:ro
